extends: [cheminfo-typescript]
rules:
  '@typescript-eslint/prefer-for-of': 'off'
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
      allow: ['ArrayConstructor']
  max-lines-per-function:
    - warn
    - max: 60
      skipBlankLines: true
      skipComments: true
overrides:
  - files: '**/__tests__/**'
    rules:
      max-lines-per-function:
        - off
